"""Catálogo explícito da etapa 07; cobertura inicial deliberadamente limitada.

O catálogo é dado JSON, independente da execução e sem inferências sobre a
correção das previsões da etapa 06. Versões históricas devem ser preservadas.
"""


def _regra(identificador, familia, descricao, *, condicoes, atributos, padrao,
           resultado, alcance, excecoes, sobreposicao, exemplos, cobertura,
           prioridade=100):
    return {
        "id": identificador, "versao": "1.0.0", "familia": familia,
        "descricao": descricao, "condicoes": condicoes + [
            "POS dos possíveis predicados do período precisa estar disponível para delimitar o alcance; ausência mantém marcador e pendência, sem interpretar null como classe não verbal."],
        "atributos_utilizados": atributos, "padrao": padrao,
        "resultado": resultado, "alcance": alcance, "excecoes": excecoes,
        "sobreposicao": sobreposicao, "exemplos": exemplos,
        "cobertura": cobertura, "prioridade": prioridade,
    }


CATALOGO = {
    "id": "lingua-etapa07", "versao": "1.0.0",
    "regras": [
        _regra("negacao_correlativa", "negacao",
               "Adição correlativa explícita não só/somente/apenas ... mas também.",
               condicoes=["Pares adjacentes não+só/somente/apenas e mas+também no mesmo período.",
                          "Marcadores adverbiais e coordenativo com núcleos sintáticos identificáveis."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id", "periodo_id"],
               padrao="não (só|somente|apenas) ... mas também; mas tem dependência cc.",
               resultado="adicao_correlativa; não atribui negação simples aos mesmos marcadores.",
               alcance="União dos tokens próprios dos predicados correlacionados, sem subordinadas de outros núcleos.",
               excecoes=["Uma expressão incompleta não dispara a regra.", "Expressões citadas sem núcleo interno permanecem ambíguas."],
               sobreposicao="Tem prioridade apenas sobre seu não e seu mas; outros marcadores continuam ativos. Suprime simples somente se habilitada.",
               exemplos=[{"texto": "Não só estudou, mas também trabalhou.", "resultado": "adicao_correlativa"},
                         {"texto": "Não só não estudou, mas também faltou.", "resultado": "adicao_correlativa e negacao_simples do segundo não"}],
               cobertura="Somente pares completos adjacentes; não contempla mas ainda, como também nem correlações elípticas.", prioridade=10),
        _regra("oracao_predicado", "oracoes", "Agrupamentos de predicados verbais e construções copulares.",
               condicoes=["POS VERB/AUX fora de dependências aux/cop, ou núcleo com filho cop."],
               atributos=["pos", "dependencia", "cabeca_token_id", "periodo_id"],
               padrao="Núcleo VERB/AUX e seus auxiliares; ADJ/NOUN/etc. com cópula dependente.",
               resultado="oracao com núcleo predicativo, auxiliares e relação com outro núcleo.",
               alcance="Subárvore própria, excluindo subárvores cujo núcleo representa outra oração; pode ser descontínua.",
               excecoes=["xcomp/ccomp constituem agrupamentos ligados, não locuções automaticamente.",
                         "Não recupera verbos elípticos nem corrige POS recebido."],
               sobreposicao="Aux/cop integram a mesma oração; relações pai/filho preservadas por vínculos. Sobreposição com outras famílias permitida.",
               exemplos=[{"texto": "Ela está feliz.", "nucleo": "feliz", "associado": "está"},
                         {"texto": "Ela está estudando.", "nucleo": "estudando", "associado": "está"},
                         {"texto": "Ela quer sair.", "nucleos": ["quer", "sair"]}],
               cobertura="Verbos, auxiliares, cópulas, conj, xcomp, ccomp, advcl, acl e csubj segundo a árvore recebida.", prioridade=20),
        _regra("negacao_nao", "negacao", "Marcador não com alcance sintático proposto.",
               condicoes=["Texto não com POS ADV/PART e dependência advmod/neg, ou ROOT incompleto, ou marcador citado mencionado."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id"],
               padrao="não dependente de predicado ou constituinte.",
               resultado="negacao_simples, com marcador e núcleo separados.",
               alcance="Tokens próprios do predicado ou subárvore do constituinte negado; ausente quando não sustentado.",
               excecoes=["Não da correlativa ativa excluído.", "Citação sem predicado interno não é atribuída ao narrador."],
               sobreposicao="Mantém cada não e vínculos com modalidade; pode participar também de multiplos_marcadores.",
               exemplos=[{"texto": "Não pensei em sair.", "nucleo": "pensei"},
                         {"texto": "Pensei em não sair.", "nucleo": "sair"}],
               cobertura="Negação explícita não; exclui nominalizações como o não quando não citadas."),
        _regra("negacao_nunca", "negacao", "Negação temporal explícita nunca.",
               condicoes=["Texto nunca com POS ADV e dependência advmod/neg, ou ROOT incompleto, ou marcador citado."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id"],
               padrao="nunca adverbial ligado ao predicado.", resultado="negacao_temporal.",
               alcance="Tokens próprios do predicado; não converte o quantificador temporal em uma data.",
               excecoes=["Menção citada conserva indeterminação."],
               sobreposicao="Mantém marcadores múltiplos sem calcular polaridade.",
               exemplos=[{"texto": "Nunca saio.", "nucleo": "saio"}],
               cobertura="Não inclui jamais, tampouco ou prefixos negativos."),
        _regra("negacao_nem", "negacao", "Negação aditiva com nem.",
               condicoes=["Texto nem adverbial/coordenativo e dependência cc/advmod/neg, ou ROOT incompleto, ou marcador citado."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id"],
               padrao="nem com dependência adverbial ou de coordenação.", resultado="negacao_aditiva.",
               alcance="Predicado próprio ou constituinte nominal coordenado identificado pela cabeça.",
               excecoes=["Não interpreta toda coordenação como negação oracional."],
               sobreposicao="Cada nem permanece individual; pode haver agrupamento de marcadores.",
               exemplos=[{"texto": "Nem João veio.", "marcador": "Nem"}],
               cobertura="Somente nem explícito; alcance nominal pode exigir contexto."),
        _regra("negacao_multiplos", "negacao", "Agrupamento de marcadores negativos no mesmo predicado.",
               condicoes=["Ao menos dois marcadores reconhecidos não/nunca/nem com mesmo núcleo e contexto de citação."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id"],
               padrao="Agrupar marcadores válidos por núcleo e região citada.", resultado="multiplos_marcadores.",
               alcance="Mesmo alcance sintático compartilhado; sem aritmética de polaridade.",
               excecoes=["Marcador não da correlativa ativa excluído.", "Não combina negadores de orações distintas."],
               sobreposicao="Sobrepõe-se intencionalmente às ocorrências negativas individuais.",
               exemplos=[{"texto": "Não saiu nunca.", "marcadores": ["Não", "nunca"]}],
               cobertura="Agrupa somente negadores explícitos com núcleo identificável."),
        _regra("tempo_flexao", "tempo", "Evidência de tempo, modo e forma verbal da anotação morfológica.",
               condicoes=["POS VERB/AUX e ao menos uma flexão Tense/Mood/VerbForm disponível."],
               atributos=["pos", "morfologia", "dependencia", "cabeca_token_id"],
               padrao="Tense, Mood e VerbForm são preservados como valores recebidos.", resultado="flexao_verbal.",
               alcance="Tokens próprios do predicado ao qual o verbo/auxiliar pertence.",
               excecoes=["Não corrige previsões morfológicas e não converte Future em data."],
               sobreposicao="Flexão e expressão relativa permanecem evidências distintas.",
               exemplos=[{"texto": "Ela saiu.", "atributo": "Tense=Past"}],
               cobertura="Somente atributos existentes; morfologia ausente gera pendência."),
        _regra("tempo_relativo", "tempo", "Referências ontem/hoje/amanhã e construção temporal quando.",
               condicoes=["Ontem/hoje/amanhã adverbiais; quando marcador de oração advcl temporal."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id"],
               padrao="Advérbios relativos ou quando/mark ligado a advcl.",
               resultado="referencia_relativa ou construcao_temporal, sem data absoluta.",
               alcance="Tokens próprios do predicado associado; marcador pode permanecer sem alcance.",
               excecoes=["Quando interrogativo não afirma conexão temporal.", "Data técnica de processamento não é referência do enunciado."],
               sobreposicao="Quando pode produzir também conector temporal.",
               exemplos=[{"texto": "Amanhã sairei.", "valor": "relativo"},
                         {"texto": "Quando chegar, avise.", "valor": "construcao_temporal"}],
               cobertura="Não inclui calendários, datas absolutas ou resolução de dêixis."),
        _regra("modalidade_verbal", "modalidade", "Modalidade proposta por verbos e construções ter que/de.",
               condicoes=["Verbo/AUX com lema poder/dever/precisar/necessitar/conseguir/saber/querer/desejar/duvidar; ter com que/de e complemento verbal."],
               atributos=["lema", "pos", "dependencia", "cabeca_token_id"],
               padrao="Lexema modal com complemento; conseguir/saber requerem complemento xcomp com VerbForm=Inf.",
               resultado="possibilidade_indeterminada, obrigacao, necessidade, capacidade, desejo ou duvida.",
               alcance="Conteúdo dos complementos xcomp/ccomp/obj/obl quando identificado; marcador separado.",
               excecoes=["Poder mantém possibilidade/permissao/capacidade.", "Dever mantém obrigacao/inferencia_epistemica.",
                         "Querer negado não comprova desejo positivo."],
               sobreposicao="Vincula negadores relevantes e agrupamentos por seus tokens; sem atribuir estado teórico ao narrador.",
               exemplos=[{"texto": "Ela pode sair.", "alternativas": ["possibilidade", "permissao", "capacidade"]},
                         {"texto": "Não quero sair.", "limitacao": "marcador modal negado"}],
               cobertura="Padrões explícitos; não resolve sentido pragmático, ironia ou capacidade sem sintaxe verbal infinitiva; saber/conseguir com ccomp não afirmam habilidade."),
        _regra("modalidade_lexical", "modalidade", "Advérbios de dúvida/possibilidade e predicados necessário/obrigatório/capaz.",
               condicoes=["Talvez/possivelmente/provavelmente adverbiais; necessário/obrigatório/capaz como predicados copulares."],
               atributos=["texto", "lema", "pos", "dependencia", "cabeca_token_id"],
               padrao="Advérbio ligado a predicado, ou adjetivo predicativo com cópula.",
               resultado="duvida, possibilidade, necessidade, obrigacao ou capacidade.",
               alcance="Predicado modificado ou conteúdo complemental do predicado copular.",
               excecoes=["Adjetivo amod de nome não dispara modalidade predicativa.", "Palavra citada não caracteriza o narrador."],
               sobreposicao="Pode coexistir com modalidades verbais e negação justificadas.",
               exemplos=[{"texto": "Talvez ela saia.", "resultado": "duvida"},
                         {"texto": "É necessário sair.", "resultado": "necessidade"}],
               cobertura="Não contempla todo vocabulário modal nem substantivos abstratos."),
        _regra("conector_simples", "conectores", "Conexões mas/porque/se/quando condicionadas à sintaxe.",
               condicoes=["Mas cc de núcleo predicativo conj; porque mark de oração; se SCONJ/mark de advcl ou condição incompleta; quando mark/advmod de advcl."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id"],
               padrao="Conector associado a um núcleo e relação sintática apropriada.",
               resultado="contraste, causa, condicao ou tempo.",
               alcance="Oração modificada; liga ao núcleo relacionado quando existente, sem fabricar unidades.",
               excecoes=["Se pronominal/reflexivo/passivador e se de ccomp interrogativo excluídos.",
                         "Mas da correlativa ativa excluído.", "Quando interrogativo excluído.", "Contraste nominal com mas, como João mas não Pedro, não integra a cobertura oracional v1."],
               sobreposicao="Quando pode sustentar tempo e conexão em ocorrências distintas.",
               exemplos=[{"texto": "Se chover, fico.", "resultado": "condicao"},
                         {"texto": "Ela se lavou.", "resultado": "sem condicao"},
                         {"texto": "Perguntei se sairia.", "resultado": "sem condicao"}],
               cobertura="Sem elipses recuperadas; condições sem consequência exigem contexto."),
        _regra("conector_por_isso", "conectores", "Consequência explícita por isso com retomada contextual.",
               condicoes=["Por e isso adjacentes no mesmo período, por/case ligado a isso e isso/obl ou advmod associado a predicado, com por isso antes do núcleo predicativo."],
               atributos=["texto", "pos", "dependencia", "cabeca_token_id", "periodo_id"],
               padrao="por isso com ligação sintática explícita e posição anterior ao predicado consequente.", resultado="consequencia.",
               alcance="Tokens próprios do predicado consequente; antecedente só ligado quando há núcleo anterior na mesma árvore.",
               excecoes=["Retomada entre períodos não inventa antecedente; registra necessidade de contexto.", "Uso pós-verbal/argumental como passei por isso fica fora da cobertura v1."],
               sobreposicao="Convive com coordenação e modalidades; não é duplicata de outra família.",
               exemplos=[{"texto": "Choveu; por isso fiquei.", "resultado": "consequencia"}],
               cobertura="Somente por isso anteposto; não inclui uso pós-verbal/argumental, portanto, logo ou por esse motivo."),
    ],
}

REGRA_IDS = tuple(regra["id"] for regra in CATALOGO["regras"])
